### PR TITLE
Add zh_Hans locale

### PR DESCRIPTION
**Pull request by daimon99**

### CODE REVIEW

**Comment by silentsokolov** [comment]
Thanks! But read [CONTRIBUTING.md](https://github.com/silentsokolov/django-admin-rangefilter/blob/master/CONTRIBUTING.md), please

**Comment by daimon99** [comment]
> Thanks! But read [CONTRIBUTING.md](https://github.com/silentsokolov/django-admin-rangefilter/blob/master/CONTRIBUTING.md), please

Oh, sorry.

**Comment by silentsokolov** [comment]
Approved 👍

**Comment by daimon99** [comment]
Ok now

**Pull request merged**
