### PR TITLE
Fixing double media loading issue

### PR DESCRIPTION
**Pull request by marcinowski**
Should fix https://github.com/silentsokolov/django-admin-rangefilter/issues/9
I've made this quick fix today, but can test it a bit more tomorrow though.

### CODE REVIEW

**Comment by silentsokolov** [comment]
Good solution, but not works with two filtres.

Test on:
```python
@admin.register(Post)
class PostAdmin(admin.ModelAdmin):
    list_display = ('name', 'created_at')
    list_editable = ('created_at',)
    list_filter = (
        'name', ('created_at', DateRangeFilter), ('updated_at', DateRangeFilter),
    )
```

**Comment by marcinowski** [comment]
image
Works for me just fine, I'm on Django 1.9.6

**Comment by silentsokolov** [comment]
Problem:


If there are no editable fields, the number of load scripts is not an problem.

**Comment by marcinowski** [comment]
image
I'm back! :D I see that this issue is still not resolved, so I thought I'd get back to it.
This time I've tested the solution on Django 2.0.5, the solution also seems a bit better, although I'm not 100% why this works.
I've tested this on the following

```python
from django.db import models
from django.contrib import admin

from rangefilter.filter import DateRangeFilter


class Post(models.Model):
    from_time = models.DateTimeField()
    to_time = models.DateTimeField()


class Comment(models.Model):
    from_time = models.DateField()
    to_time = models.DateField()


@admin.register(Post)
class PostAdmin(admin.ModelAdmin):
    list_display = ('from_time', 'to_time')
    list_editable = ('from_time', 'to_time')
    list_display_links = None
    list_filter = (
        ('from_time', DateRangeFilter), ('to_time', DateRangeFilter)
    )


@admin.register(Comment)
class CommentAdmin(admin.ModelAdmin):
    list_display = ('from_time', 'to_time')
    list_editable = ('from_time', 'to_time')
    list_display_links = None
    list_filter = (
        ('from_time', DateRangeFilter), ('to_time', DateRangeFilter)
    )
```

**Comment by marcinowski** [comment]
Ok, I've found the issue myself, commenting out the `list_editable` removes the widget from `filters`, damn it

**Comment by marcinowski** [comment]
Ok, I think I've finally figured it out. 
How it worked:
     - First Django loads the model formset with predefined widgets for different
       field types. If there's a date based field, then it loads the _AdminDateWidget_
       and it's required media to context under `{{media.js}}` in _templates/admin/change_list.html_.
       (Note: it accumulates media in _django.forms.widgets.Media object_,
       which prevents duplicates, but the _DateRangeFilter_ is not included yet
       since it's not model field related.
       List of predefined widgets is in _django.contrib.admin.options.FORMFIELD_FOR_DBFIELD_DEFAULTS_)
     - After that Django starts rendering forms, which have the `{{form.media}}`
       tag. Only then the `DjangoRangeFilter.get_media()` is called and rendered,
       which creates the duplicates.
How it works:
     - first step is the same, if there's a _AdminDateWidget_ to be loaded then
       nothing changes
     - DOM gets rendered and if the _AdminDateWidget_ was rendered then
       the _DateTimeShortcuts.js_ is initiated which sets the `window.DateTimeShortcuts`.
       Otherwise, the `window.DateTimeShortcuts` is undefined.
     - The lines below check if the `DateTimeShortcuts` has been set and if not
       tthen the _DateTimeShortcuts.js_ and _calendar.js_ is rendered
     - if there's more than one _DateRangeFilter_ then the only the first {{form.media.js}} will return the static js files, all the subsequent requests will return []. This happens by setting a `DJANGO_RANGEFILTER_ADMIN_JS_SET` on request.

How it could work:
     - in `DateTimeShortcuts.js` the `init` method is attached to the eventListener on `loads`. It doesn't check if it has been done previously, that's why we get multiple identical objects listening on `loads`. So in `admin/js/admin/DateTimeShortcuts.js` instead of 
```javascript
    window.addEventListener('load', DateTimeShortcuts.init);
    window.DateTimeShortcuts = DateTimeShortcuts;
```
it should be 
```javascript
 if (window.DateTimeShortuts == 'undefined') {
    window.addEventListener('load', DateTimeShortcuts.init);
    window.DateTimeShortcuts = DateTimeShortcuts;
 }
```

**Comment by marcinowski** [comment]
Tested on the following:

```python
from django.db import models
from django.contrib import admin

from rangefilter.filter import DateRangeFilter, DateTimeRangeFilter


class Post(models.Model):
    from_time = models.DateTimeField()
    to_time = models.DateTimeField()


class Comment(models.Model):
    from_time = models.DateField()
    to_time = models.DateField()


@admin.register(Post)
class PostAdmin(admin.ModelAdmin):
    list_display = ('from_time', 'to_time')
    list_display_links = None
    list_filter = (
        ('from_time', DateTimeRangeFilter),
        ('to_time', DateTimeRangeFilter),
        ('to_time', DateTimeRangeFilter),
        ('to_time', DateTimeRangeFilter),
        ('to_time', DateTimeRangeFilter),
    )


@admin.register(Comment)
class CommentAdmin(admin.ModelAdmin):
    list_display = ('from_time', 'to_time')
    list_editable = ('from_time', 'to_time')
    list_display_links = None
    list_filter = (
        ('from_time', DateRangeFilter),
        ('to_time', DateRangeFilter),
        ('to_time', DateRangeFilter),
        ('to_time', DateRangeFilter),
        ('to_time', DateRangeFilter),
    )
```
AdminDateFilter included in editable
image

Statics loaded:
image

AdminDateFilter not included in editable
image

**Comment by silentsokolov** [comment]
Unbelievable! It's work! 🎉
@marcinowski thank you very much for the work done!

**Pull request merged**
