### PR TITLE
Use admin CSS vars for colors

### PR DESCRIPTION
**Pull request by mharju**
Hi!

A simple fix to use the CSS variables to set the colors used in the buttons. Needed this for branding so if it's useful upstream, here it is.

Thanks!

### CODE REVIEW

**Comment by silentsokolov** [comment]
A good improvement, thanks you. But it doesn't work on django version 3 ((

**Comment by mharju** [comment]
You're right! Maybe I'll add a check to see if we are running Django < 3.2 and set default values for the CSS variables?

**Comment by silentsokolov** [comment]
> You're right! Maybe I'll add a check to see if we are running Django < 3.2 and set default values for the CSS variables?

That sounds good

**Comment by mharju** [comment]
The list filter does not expose template context so I had to make a templatetag to fill in the variables.

How does this look to you?

**Comment by silentsokolov** [comment]
Thanks!

**Pull request merged**
